LW-1073 Add renewable column
ndlib/usurper pull request #1032
Opened 2021-03-10 19:38 UTC by pweikel

Would appreciate some feedback on this. Especially on the efficacy of [this unit test](https://github.com/ndlib/usurper/pull/1032/files#diff-f47adfe15c9e458fb9ac568c8cdc3e22e3cdb2166af3b7d869f252a61d647e9eR59).

2021-03-10 20:01 UTC, danthewolfe approved these changes

2021-03-10 21:26 UTC, mlkirkpatrick requested changes

2021-03-10 21:26 UTC, mlkirkpatrick commented on src/components/Account/ResourceList/Resource/Cards/index.js
> +        } else {
The text "Yes" and "No" is a pretty generic string representation for a boolean; that's a good thing, but the way it's written here you won't immediately get that benefit if another boolean is added. There really isn't a reason to qualify it with `key === 'renewable'`, unless you want the value to be something special for this field which would _not_ apply to other booleans.

2021-03-10 21:26 UTC, mlkirkpatrick commented on src/components/Account/ResourceList/Resource/Cards/index.js
> +        }
You _could_ set the value to a component here, but I wouldn't because it mixes the data type of `value` so that it is sometimes a string and sometimes a component. It also makes the previous code that sets the value to 'Yes' or 'No' irrelevant. Even if you did do it here, you wouldn't need to check if it is a boolean because you know that renewable **is** in fact a boolean.

I think it's more readable if you instead leave value as a simple string, and set another variable for the component it renders based on the key. It already does this with the "from" field, where it renders an <FromIcon> instead of the standard <span>; you just need one more if condition (or a switch case) to check if it's the "renewable" field, and if so render the ToolTip. (Also you would pass the value variable in to the prop, instead of hardcoding the yes and no a second time.)

2021-03-10 21:26 UTC, mlkirkpatrick commented on src/components/Account/ResourceList/Resource/Cards/style.module.css
> +
Have you tested this on a small screen (mobile view)? I think some columns are hidden there so it might require a little more css than just this. I could be wrong though.

2021-03-10 21:26 UTC, mlkirkpatrick commented on src/components/Account/ResourceList/style.module.css
>      -ms-grid-columns: 2fr 1fr 1fr .5fr .25fr;
You added a new column so this should be specifying six instead of five.

2021-03-10 21:26 UTC, mlkirkpatrick commented on src/tests/components/Account/ResourceList/Resource/Cards/index.test.js
>            }
This code block will never run because renewable is not a string and none of the other columns are called 'renewable'. I think this should just be an `else` so it will run for all columns except title and renewable.

2021-03-10 21:26 UTC, mlkirkpatrick commented on src/tests/components/Account/ResourceList/Resource/ToolTip/index.test.js
> +  })
I don't like searching for exact text that is hardcoded because it often gets tweaked and it's not important to the test. Use `expect.any(String)` instead.

2021-03-10 21:26 UTC, mlkirkpatrick commented on src/components/Account/ResourceList/Resource/ToolTip/index.js
> +  const toolTip = (props.value === 'No' ? 'Renewal not available. Please return by due date.' : 'Please click the "view in ILL" button to renew')
Be consistent with punctuation; add a period to the end of the "Yes" message.

2021-03-12 16:01 UTC, pweikel reviewed
I was going to reply to each comment directly but the option to do so doesn't seem to be working for some reason. I've addressed the feedback and update that PR.

2021-03-12 19:05 UTC, mlkirkpatrick requested changes

2021-03-12 19:05 UTC, mlkirkpatrick commented on src/tests/components/Account/ResourceList/Resource/ToolTip/index.test.js
> +  })
The description for these mention a "renewable column" and "ILL items." This happens to be the context in which it is used right now, but technically the ToolTip component doesn't know or care about any of these details. All it does is display a string appropriate for the value passed to it.

Additionally, these tests don't do anything. You're expecting a string but it's not even looking at the enzymeWrapper. You have to expect a string _inside of_ some element, whether that is a span, div, some other component, etc. For example:
```
const element = enzymeWrapper.find('span')
expect(element.exists()).toBe(true)
expect(element.text()).toEqual(expect.any(String))
```

Now along those lines, I think that you should test that the string for the true value and the false value are not the same string, otherwise you can't be sure that the value prop actually does anything; it might just be broken and it's always returning the false string, for example.

You can either do this by making your existing tests more specific so they actually do care about _part_ of the string, or you can make a thid test where you create two wrappers and just compare them to ensure the string inside them is not the same.

2021-03-12 19:05 UTC, mlkirkpatrick commented on src/tests/components/Account/ResourceList/Resource/Cards/index.test.js
> +          } else if (column !== 'renewable' || 'title') {
The "Not Available" is a byproduct of changing the type to ILL; there are already test cases specifically for ILL items, so you shouldn't be changing this one from NDU. By doing this, you are no longer testing NDU items and whether they get a return date or not.

Also, the last if condition is unnecessary and incorrect. We're already chaining conditions, so you don't need to check if it's not renewable because the check for if it is renewable is above. You also can't do a not comparison with an or operator like that; this would return true if the column value was 'title' because the string 'title' is truthy. What you meant was `column !== 'renewable' && column !== 'title'`, but I just explained that the whole if condition is unnecessary anyway. :)

2021-03-12 20:39 UTC, pweikel commented on src/tests/components/Account/ResourceList/Resource/ToolTip/index.test.js
> +  })
Okay. I follow you. I've updated the the test titles to be more generic and the parameters to be more or less specific.

2021-03-16 17:30 UTC, pweikel commented on src/components/Account/ResourceList/Resource/Cards/index.js
> +          return <ToolTip key={key} value={props.item[key]} />
I took your advice and revised this to pass the prop value prop to the component

2021-03-16 17:38 UTC, pweikel commented on src/tests/components/Account/ResourceList/Resource/Cards/index.test.js
> +          } else if (column !== 'renewable' || 'title') {
`          } else if (column !== 'renewable') {
            const found = enzymeWrapper.findWhere(el => el.type() === Card && el.props().value === props.item[column])
            expect(found.exists()).toBe(true)`
Thank you for explaining the logic there. I believe that I modified the unit test so that it looks at the columns that have not yet been reviewed.

2021-03-16 17:38 UTC, pweikel commented on src/tests/components/Account/ResourceList/Resource/ToolTip/index.test.js
> +  })
Updated the unit test to look for part of the string instead of the whole string.

2021-03-16 17:53 UTC, mlkirkpatrick requested changes
Close. :) Just a couple more changes to the unit tests and then this looks good.

2021-03-16 17:53 UTC, mlkirkpatrick commented on src/tests/components/Account/ResourceList/Resource/Cards/index.test.js
> +            expect(enzymeWrapper.find(ToolTip).exists()).toBe(true)
This will never execute since the test case is for an item from NDU, not ILL. You need to make a new test case with an ILL item and check for the ToolTip.

2021-03-16 17:53 UTC, mlkirkpatrick commented on src/tests/components/Account/ResourceList/Resource/Cards/index.test.js
>              expect(found.exists()).toBe(true)
What about testing the renewable column? We should expect that true or false get converted to "Yes" and "No", so I would at least check that the renewable column displays _some_ string and not just an empty cell, to ensure the conversion from bool to string works.

2021-03-16 17:53 UTC, mlkirkpatrick commented on src/components/Account/ResourceList/Resource/Cards/index.js
> +          return <ToolTip key={key} title={props.item.title} value={props.item[key]} />
Just to point out: `key` isn't needed as a prop here, but it's not doing any harm either. You typically only need this when looping through an array.

2021-03-18 14:34 UTC, pweikel commented on src/tests/components/Account/ResourceList/Resource/Cards/index.test.js
>              expect(found.exists()).toBe(true)
Got it. I added a test to look for the string in the renewable column.

2021-03-18 14:34 UTC, pweikel commented on src/tests/components/Account/ResourceList/Resource/Cards/index.test.js
> +            expect(enzymeWrapper.find(ToolTip).exists()).toBe(true)
Okay. I made a[ separate test](https://github.com/ndlib/usurper/pull/1032/files#diff-f47adfe15c9e458fb9ac568c8cdc3e22e3cdb2166af3b7d869f252a61d647e9eR95) for the ToolTip.

2021-03-18 14:39 UTC, mlkirkpatrick approved these changes

2021-03-18 14:39 UTC, mlkirkpatrick commented on src/tests/components/Account/ResourceList/Resource/Cards/index.test.js
> +            expect(found.contains(<span className="detailValue">No</span>)).toBe(true)
I'd prefer not including the `className="detailValue"` on this. You can test just the text with:
```
expect(found.text()).toEqual('No')
```

2021-03-18 15:02 UTC, mlkirkpatrick approved these changes

2021-03-18 15:03 UTC, pweikel commented on src/tests/components/Account/ResourceList/Resource/Cards/index.test.js
> +            expect(found.contains(<span className="detailValue">No</span>)).toBe(true)
changed to: `expect(found.containsMatchingElement(<span>{expect.any(String)}</span>)).toBe(true)`

2021-03-18 15:03 UTC, merged