updated Event schema
ndlib/usurper pull request #1120
Opened 2021-09-16 19:33 UTC by pweikel

Updated some fields within the Event schema

2021-09-16 20:00 UTC, mlkirkpatrick requested changes

2021-09-16 20:00 UTC, mlkirkpatrick commented on src/components/Contentful/Event/presenter.js
> +      <meta itemProp='audience' content={entry.audience} />
I don't think this field will work very well as-is. `entry.audience` is an array of strings. The schema probably expects a structured object and a single string for the audience name.

2021-09-22 18:53 UTC, pweikel commented on src/components/Contentful/Event/presenter.js
> +      <meta itemProp='audience' content={entry.audience} />
You're right about this. It does appear that the schema expects a single string so this data point doesn't look like it will work for this purpose. If it accepted multiple strings, we could have used it, but that's not the case.

2021-09-22 18:57 UTC, mlkirkpatrick requested changes

2021-09-22 18:57 UTC, mlkirkpatrick commented on src/components/Contentful/Event/presenter.js
> +          <Sponsorships itemProp='sponsor' content={entry.sponsors} />
`itemProp` needs to go on an HTML element, not the React component. If you put it here, it just passes as a prop, and then the React component needs to pass it down further. You might as well build it right into the component to include the itemProp on a div.

2021-09-22 18:57 UTC, mlkirkpatrick commented on src/components/Sponsorships/index.js
> +  if (!content) {
I'm not sure why you changed the name of this prop. It seems like maybe you were going to pass the meta tag inside it? I don't think that's necessary, as you can just include the meta tag directly in the rendered output instead of needing to pass it in.

2021-09-22 19:09 UTC, pweikel commented on src/components/Contentful/Event/presenter.js
> +          <meta itemProp='sponsor' content={entry.sponsors} />
Good call. I updated the `Sponsorships` component to use the content property so that it is compatible with the schema property. Also, I noticed the `Sponsorships` component didn't have unit tests so I added those.

2021-09-22 19:20 UTC, pweikel commented on src/components/Contentful/Event/presenter.js
> +          <Sponsorships itemProp='sponsor' content={entry.sponsors} />
I follow you. I was thinking that it would best to have all the props for Event in the same component, but now I see that it will still be within the scope of the Event schema even tho it is rendered in the Sponsorships component.

2021-09-22 19:20 UTC, pweikel commented on src/components/Sponsorships/index.js
> +  if (!content) {
Acting your previous advice, I've updated the location of the itemProp into the Sponsorships component and reverted the name of this prop.

2021-09-22 19:48 UTC, mlkirkpatrick approved these changes

2021-09-23 16:03 UTC, mlkirkpatrick approved these changes

2021-09-23 17:34 UTC, danthewolfe approved these changes

2021-09-23 17:34 UTC, merged